export const LOAD_MEMBER_COUNT_SUCCESS = "LOAD_MEMBER_COUNT_SUCCESS";
export const LOAD_MOST_USED_KEYWORDS_SUCCESS =
  "LOAD_MOST_USED_KEYWORDS_SUCCESS";
export const LOAD_SAT_SUCCESS = "LOAD_SAT_SUCCESS";
